package com.example.makemovie.service;

import com.example.makemovie.entity.*;
import com.example.makemovie.repository.MaterialRepository;
import com.example.makemovie.enums.StepStatus;
import com.example.makemovie.enums.WorkflowStep;
import com.example.makemovie.exception.BusinessException;
import com.example.makemovie.repository.*;
import com.example.makemovie.service.model.TimelineSegment;
import io.minio.GetObjectArgs;
import io.minio.MinioClient;
import io.minio.PutObjectArgs;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;

import java.util.ArrayList;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;
import java.util.UUID;

@Slf4j
@Service
@RequiredArgsConstructor
public class VideoComposerService {

    private final MinioClient minioClient;
    private final StoryboardRepository storyboardRepository;
    private final StoryboardFrameRepository frameRepository;
    private final CompositionRepository compositionRepository;
    private final CompositionTaskRepository taskRepository;
    private final ProjectRepository projectRepository;
    private final MaterialRepository materialRepository;
    private final WorkflowLogService workflowLogService;
    private final ProgressService progressService;
    private final SubtitleService subtitleService;
    private final FfmpegCommandBuilder ffmpegCommandBuilder;

    @Value("${storage.temp-dir:./temp}")
    private String tempDir;

    @Value("${minio.bucket-name:assets}")
    private String bucketName;

    @Value("${video.composition.max-parallel-tasks:2}")
    private int maxParallelTasks;

    /**
     * Submit a composition task (called from Controller).
     * Creates a QUEUED CompositionTask — actual processing happens in Scheduler.
     */
    @Transactional
    public UUID submitComposition(UUID projectId) {
        Storyboard storyboard = storyboardRepository.findByProjectId(projectId)
                .orElseThrow(() -> new BusinessException("STORYBOARD_NOT_FOUND",
                        "请先生成分镜"));

        // Check if there's already a composition
        List<Composition> existing = compositionRepository.findByProjectId(projectId);
        Composition composition;
        if (!existing.isEmpty()) {
            composition = existing.get(0);
            composition.setStatus("PENDING");
            composition.setProgress(0);
            compositionRepository.save(composition);
        } else {
            composition = Composition.builder()
                    .projectId(projectId)
                    .storyboardId(storyboard.getId())
                    .status("PENDING")
                    .build();
            composition = compositionRepository.save(composition);
        }

        CompositionTask task = CompositionTask.builder()
                .compositionId(composition.getId())
                .status("QUEUED")
                .build();
        task = taskRepository.save(task);

        log.info("Composition submitted: projectId={}, taskId={}", projectId, task.getId());
        return task.getId();
    }

    /**
     * Execute final composition: concat pre-generated video clips + subtitles + BGM.
     * This is V2 — no more TTS, timeline assembly, or image overlay. All assets
     * (voice audio, video clips) are pre-generated by VoiceGenerationService and
     * ClipGenerationService.
     */
    public void execute(CompositionTask task) {
        UUID taskId = task.getId();
        UUID compositionId = task.getCompositionId();
        Composition composition = compositionRepository.findById(compositionId)
                .orElseThrow();

        try {
            updateTask(task, "PROCESSING", 5, null);

            UUID projectId = composition.getProjectId();
            Storyboard storyboard = storyboardRepository.findById(composition.getStoryboardId())
                    .orElseThrow();
            List<StoryboardFrame> frames = frameRepository
                    .findByStoryboardIdOrderByFrameNumber(storyboard.getId());

            if (frames.isEmpty()) {
                throw new BusinessException("NO_FRAMES", "分镜没有帧，无法合成");
            }

            composition.setCompositionType("FINAL");
            task.setTotalFrames(frames.size());

            // Step 1: Prepare clip paths (30%)
            updateTask(task, "PROCESSING", 30, "准备视频片段...");
            Path workDir = Path.of(tempDir, "composition", projectId.toString());
            Files.createDirectories(workDir);

            List<String> clipPaths = new ArrayList<>();
            List<String> audioPaths = new ArrayList<>();
            List<String> subtitleTexts = new ArrayList<>();
            List<Double> durations = new ArrayList<>();

            for (StoryboardFrame frame : frames) {
                task.setCurrentFrame(frame.getFrameNumber());

                // Download video clip
                String clipPath = resolveToLocalPath(frame.getClipVideoUrl(), workDir,
                        generatePlaceholderClip(workDir));
                clipPaths.add(clipPath);

                // Download voice audio
                String audioPath = resolveToLocalPath(frame.getVoiceAudioUrl(), workDir,
                        generateSilentAudio(workDir, frame.getDurationSec()));
                audioPaths.add(audioPath);

                subtitleTexts.add(frame.getSubtitleText() != null
                        ? frame.getSubtitleText() : "");
                durations.add(frame.getDurationSec() != null
                        ? frame.getDurationSec() : 3.0);
            }

            // Step 2: Generate subtitles (50%)
            updateTask(task, "PROCESSING", 50, "生成字幕...");
            List<TimelineSegment> segments = buildSimpleSegments(
                    frames, clipPaths, audioPaths, durations);
            String subtitlePath = subtitleService.generate(segments, projectId.toString());

            // Step 3: Resolve BGM if selected
            String bgmPath = null;
            if (composition.getBgmMaterialId() != null) {
                try {
                    Material bgmMaterial = materialRepository.findById(composition.getBgmMaterialId())
                            .orElse(null);
                    if (bgmMaterial != null && bgmMaterial.getUrl() != null) {
                        bgmPath = resolveToLocalPathStr(bgmMaterial.getUrl());
                        log.info("BGM resolved: {} -> {}", bgmMaterial.getName(), bgmPath);
                    }
                } catch (Exception e) {
                    log.warn("Failed to resolve BGM: {}", e.getMessage());
                }
            }

            // Step 4: FFmpeg concat (60-90%)
            updateTask(task, "PROCESSING", 60, "合成视频中...");
            Path outputPath = Path.of(tempDir, "output", projectId + ".mp4");
            Files.createDirectories(outputPath.getParent());

            List<String> ffmpegCmd = ffmpegCommandBuilder.buildConcatCommand(
                    clipPaths, audioPaths, subtitleTexts, subtitlePath,
                    bgmPath, outputPath.toString());

            String cmdStr = String.join(" ", ffmpegCmd);
            task.setFfmpegCommand(cmdStr.length() > 2000
                    ? cmdStr.substring(0, 2000) : cmdStr);
            taskRepository.save(task);

            int exitCode = runFfmpeg(ffmpegCmd, task);
            if (exitCode != 0) {
                throw new BusinessException("FFMPEG_FAILED",
                        "FFmpeg exited with code " + exitCode);
            }

            // Step 4: Upload (95%)
            updateTask(task, "PROCESSING", 95, "上传视频...");
            String videoUrl = uploadToMinio(outputPath, projectId);
            composition.setVideoUrl(videoUrl);
            composition.setProgress(100);
            composition.setStatus("COMPLETED");
            composition.setDurationSec((int) durations.stream()
                    .mapToDouble(Double::doubleValue).sum());
            compositionRepository.save(composition);

            updateTask(task, "COMPLETED", 100, null);

            // Update workflow
            workflowLogService.updateStatus(composition.getProjectId(),
                    WorkflowStep.FINAL_COMPOSITION, StepStatus.COMPLETED,
                    Map.of("frames", frames.size()),
                    Map.of("videoUrl", composition.getVideoUrl(),
                            "durationSec", composition.getDurationSec()),
                    0);

            Project project = projectRepository.findById(composition.getProjectId())
                    .orElseThrow();
            progressService.refreshProgress(project);

            // Auto-trigger: COPYWRITING
            workflowLogService.updateStatus(composition.getProjectId(),
                    WorkflowStep.COPYWRITING, StepStatus.RUNNING,
                    Map.of("videoUrl", composition.getVideoUrl()), null, 0);
            progressService.refreshProgress(project);

            log.info("Final composition complete: taskId={}, output={}", taskId, outputPath);

        } catch (Exception e) {
            log.error("Composition failed: taskId={}", taskId, e);
            updateTask(task, "FAILED", 0, e.getMessage());
            composition.setStatus("FAILED");
            compositionRepository.save(composition);
        }
    }

    private int runFfmpeg(List<String> command, CompositionTask task)
            throws IOException, InterruptedException {
        ProcessBuilder pb = new ProcessBuilder(command);
        pb.redirectErrorStream(true);
        Process process = pb.start();

        StringBuilder logBuilder = new StringBuilder();
        try (BufferedReader reader = new BufferedReader(
                new InputStreamReader(process.getInputStream()))) {
            String line;
            while ((line = reader.readLine()) != null) {
                logBuilder.append(line).append("\n");
                // Trim log to prevent overflow
                if (logBuilder.length() > 10000) {
                    logBuilder.delete(0, logBuilder.length() - 8000);
                }
            }
        }

        int exitCode = process.waitFor();
        task.setFfmpegLog(logBuilder.toString());
        taskRepository.save(task);
        return exitCode;
    }

    private void updateTask(CompositionTask task, String status,
                             int progress, String message) {
        task.setStatus(status);
        task.setProgress(progress);
        if (message != null) task.setErrorMessage(message);
        if ("PROCESSING".equals(status) && task.getStartedAt() == null) {
            task.setStartedAt(LocalDateTime.now());
        }
        if ("COMPLETED".equals(status) || "FAILED".equals(status)) {
            task.setCompletedAt(LocalDateTime.now());
        }
        taskRepository.save(task);

        // Also update parent composition progress
        Composition comp = compositionRepository.findById(task.getCompositionId())
                .orElse(null);
        if (comp != null) {
            comp.setProgress(progress);
            compositionRepository.save(comp);
        }
    }

    /**
     * Public overload: resolve a URL to a local path string using a temp work directory.
     * Used by MaterialController for streaming material files and download endpoint.
     */
    public String resolveToLocalPathStr(String url) {
        try {
            Path workDir = Path.of(tempDir, "material");
            Files.createDirectories(workDir);
            return resolveToLocalPath(url, workDir, null);
        } catch (Exception e) {
            log.warn("resolveToLocalPath failed for {}: {}", url, e.getMessage());
            return null;
        }
    }

    /**
     * Resolve minio:// or file:// URL to a local path. Downloads from MinIO if needed.
     */
    private String resolveToLocalPath(String url, Path workDir, Path fallback) {
        if (url == null || url.isBlank()) return fallback.toString();
        try {
            if (url.startsWith("file://")) {
                String path = url.substring(7);
                if (Files.exists(Path.of(path))) return path;
            }
            if (url.startsWith("minio://")) {
                String rest = url.substring("minio://".length());
                int slashIdx = rest.indexOf('/');
                String bucket = rest.substring(0, slashIdx);
                String object = rest.substring(slashIdx + 1);
                Path localFile = workDir.resolve(object.replace('/', '_'));
                if (!Files.exists(localFile)) {
                    try (var is = minioClient.getObject(
                            GetObjectArgs.builder().bucket(bucket).object(object).build())) {
                        Files.copy(is, localFile);
                    }
                }
                return localFile.toString();
            }
            if (Files.exists(Path.of(url))) return url;
        } catch (Exception e) {
            log.debug("Cannot resolve {}: {}", url, e.getMessage());
        }
        return fallback.toString();
    }

    private int estimateTotalDuration(List<TimelineSegment> segments) {
        return (int) Math.ceil(segments.stream()
                .mapToDouble(TimelineSegment::totalDurationSec).sum());
    }

    private List<TimelineSegment> buildSimpleSegments(
            List<StoryboardFrame> frames,
            List<String> clipPaths,
            List<String> audioPaths,
            List<Double> durations) {
        List<TimelineSegment> segments = new ArrayList<>();
        for (int i = 0; i < frames.size(); i++) {
            StoryboardFrame frame = frames.get(i);
            double dur = durations.get(i);
            segments.add(new TimelineSegment(
                    i, frame.getId(), frame.getSceneId(),
                    clipPaths.get(i), frame.getBgImageUrl(),
                    List.of(),
                    audioPaths.get(i), dur, 0.0, 0.0, dur,
                    frame.getSubtitleText() != null ? frame.getSubtitleText() : "",
                    frame.getTransition() != null ? frame.getTransition() : "cut",
                    frame.getShotType() != null ? frame.getShotType() : "MS"));
        }
        return segments;
    }

    private Path generatePlaceholderClip(Path workDir) throws IOException, InterruptedException {
        Path placeholder = workDir.resolve("_placeholder_clip.mp4");
        if (!Files.exists(placeholder)) {
            new ProcessBuilder(
                    "ffmpeg", "-y", "-f", "lavfi",
                    "-i", "color=c=0x1a1a2e:s=1080x1920:d=3:r=30",
                    "-c:v", "libx264", "-preset", "ultrafast",
                    "-t", "3", placeholder.toString()
            ).start().waitFor();
        }
        return placeholder;
    }

    private Path generateSilentAudio(Path workDir, Double durationSec)
            throws IOException, InterruptedException {
        Path silent = workDir.resolve("_silence_" + durationSec + ".mp3");
        if (!Files.exists(silent)) {
            new ProcessBuilder(
                    "ffmpeg", "-y", "-f", "lavfi",
                    "-i", "anullsrc=r=44100:cl=mono",
                    "-t", String.valueOf(durationSec),
                    "-c:a", "libmp3lame", silent.toString()
            ).start().waitFor();
        }
        return silent;
    }

    /**
     * Upload the output video to MinIO (or fallback to local file://).
     */
    private String uploadToMinio(Path videoPath, UUID projectId) {
        try {
            byte[] videoBytes = Files.readAllBytes(videoPath);
            String objectName = "videos/" + projectId + ".mp4";

            try {
                minioClient.putObject(PutObjectArgs.builder()
                        .bucket(bucketName)
                        .object(objectName)
                        .stream(new java.io.ByteArrayInputStream(videoBytes),
                                videoBytes.length, -1)
                        .contentType("video/mp4")
                        .build());
                String url = "minio://" + bucketName + "/" + objectName;
                log.info("Video uploaded to MinIO: {}", url);
                return url;
            } catch (Exception e) {
                // Fallback to local file system
                String localUrl = videoPath.toUri().toString();
                log.warn("MinIO upload failed, using local path: {} — {}", localUrl, e.getMessage());
                return localUrl;
            }
        } catch (Exception e) {
            log.error("Failed to read video file for upload: {}", e.getMessage());
            return videoPath.toUri().toString();
        }
    }

    public Composition getComposition(UUID projectId) {
        List<Composition> list = compositionRepository.findByProjectId(projectId);
        if (list.isEmpty()) {
            throw new BusinessException("COMPOSITION_NOT_FOUND", "未找到合成记录");
        }
        return list.get(0);
    }

    public CompositionTask getTask(UUID compositionId) {
        List<CompositionTask> tasks = taskRepository.findByCompositionId(compositionId);
        if (tasks.isEmpty()) {
            throw new BusinessException("TASK_NOT_FOUND", "未找到合成任务");
        }
        return tasks.get(tasks.size() - 1);
    }
}
